spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  security:
    user:
      name: user
      password: '1111'

jwt:
  expiration_time: 86400000
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
